/**
 * Field-level copy for the /setup/review form editor (Stream 3).
 *
 * Each entry binds a `(sectionId, fieldKey)` to:
 *   - label:       short Title-Case label shown above the input
 *   - help:        one-sentence guidance shown beneath the input (muted)
 *   - placeholder: ghost text inside the input itself
 *
 * Granular `(section, field)` entries cover `company_context.yaml` because
 * its schema is deterministic — see `src/lib/framework/context-types.ts`
 * (`CompanyContext`). The synthesized YAML/Markdown/text sections are
 * mostly long-form prose generated by the LLM with shape that varies run
 * to run. For those we surface a single coarse "file" entry under the
 * synthetic field name `__file__` so the editor can render a labeled
 * textarea over the raw body without inventing fields the schema doesn't
 * pin down.
 *
 * Field keys mirror the dotted path inside the parsed YAML (e.g.
 * `company.name`, `icp.segments_freeform`). Array fields use `[]` to
 * indicate a list (e.g. `icp.pain_points[]`). The editor renders these as
 * one-item-per-line textareas.
 */

export interface FieldHelp {
  label: string
  help: string
  placeholder?: string
}

export type SectionFieldHelp = Record<string, FieldHelp>

export const SETUP_FIELD_HELP: Record<string, SectionFieldHelp> = {
  // ── Captured ─────────────────────────────────────────────────────────────
  company_context: {
    'company.name': {
      label: 'Company name',
      help: 'Required. The legal or trading name of the company we are running GTM for.',
      placeholder: 'Acme Inc.',
    },
    'company.website': {
      label: 'Website',
      help: 'Primary marketing site. Used as a content source for synthesis.',
      placeholder: 'https://acme.com',
    },
    'company.description': {
      label: 'Description',
      help: 'One or two sentences on what the company does. Drives positioning.',
      placeholder: 'Acme builds payment infra for B2B marketplaces.',
    },
    'company.industry': {
      label: 'Industry',
      help: 'Optional. Free-form industry tag (Fintech, HR Tech, DevTools, etc.).',
      placeholder: 'Fintech',
    },
    'company.stage': {
      label: 'Stage',
      help: 'Optional. Funding or maturity stage (pre-seed, Series A, public, etc.).',
      placeholder: 'Series A',
    },
    'company.team_size': {
      label: 'Team size',
      help: 'Optional. Approximate headcount (e.g. 1-10, 25, 100+).',
      placeholder: '25',
    },
    'founder.name': {
      label: 'Founder name',
      help: 'The person whose voice and signal we anchor outbound on.',
      placeholder: 'Jane Doe',
    },
    'founder.linkedin': {
      label: 'Founder LinkedIn',
      help: 'Profile URL — used for tone extraction and as a connection origin.',
      placeholder: 'https://linkedin.com/in/janedoe',
    },
    'icp.segments_freeform': {
      label: 'ICP segments (free-form)',
      help: 'Required (or fill the structured list below). Plain-English description of who you are targeting.',
      placeholder: 'Heads of RevOps at 50-500 person B2B SaaS in North America.',
    },
    'icp.pain_points[]': {
      label: 'Pain points',
      help: 'One pain point per line. Drives qualification and message angles.',
      placeholder: 'Manual lead routing\nNo unified view of pipeline\nForecast slips week over week',
    },
    'icp.competitors[]': {
      label: 'Competitors',
      help: 'One competitor per line. Synthesis builds a battlecard per entry.',
      placeholder: 'Clay\nApollo\nClearbit',
    },
    'icp.subreddits[]': {
      label: 'Subreddits',
      help: 'One per line, lowercase, no `r/` prefix. Where this audience hangs out on Reddit.',
      placeholder: 'sales\nsaas\nrevops',
    },
    'icp.target_communities[]': {
      label: 'Target communities',
      help: 'Slack groups, LinkedIn communities, Discord servers, etc. — one per line.',
      placeholder: 'Pavilion\nRevGenius\nModern Sales Pros',
    },
    'voice.description': {
      label: 'Voice description',
      help: 'How you sound when you write. One paragraph is plenty — synthesis will refine it.',
      placeholder: 'Direct, technical, allergic to fluff. Short sentences. No emojis.',
    },
    'voice.examples_path': {
      label: 'Voice examples path',
      help: 'Optional. Local file path where your sample writing lives (used at capture time only).',
      placeholder: '/Users/me/voice-samples.md',
    },
    'sources.website': {
      label: 'Source · website',
      help: 'URL that was scraped at capture time. Mostly informational.',
    },
    'sources.linkedin': {
      label: 'Source · LinkedIn',
      help: 'LinkedIn profile or company page used as a source.',
    },
    'sources.linkedin_account_id': {
      label: 'Unipile account id',
      help: 'Unipile account whose LinkedIn engagement we harvest. Set via `provider:add unipile`.',
    },
    'sources.docs[]': {
      label: 'Source · docs',
      help: 'One file or folder path per line. Local docs read at capture time.',
      placeholder: '/Users/me/docs/positioning.md',
    },
    'sources.voice': {
      label: 'Source · voice samples',
      help: 'Path to the voice samples used for tone extraction.',
    },
    'meta.captured_at': {
      label: 'Captured at',
      help: 'Timestamp set when capture first ran. Read-only.',
    },
    'meta.last_updated_at': {
      label: 'Last updated at',
      help: 'Timestamp of the last edit. Updated on save.',
    },
    'meta.version': {
      label: 'Version',
      help: 'YALC schema version that authored the file. Read-only.',
    },
  },

  // ── Synthesized ──────────────────────────────────────────────────────────
  // YAML shapes vary run-to-run because they come from the LLM. We expose
  // a single labeled textarea per file rather than invent fields.
  framework: {
    __file__: {
      label: 'GTM framework (YAML)',
      help: 'Synthesized from your captured context. Edits here flow into every framework module that reads `framework.yaml`.',
    },
  },
  voice: {
    __file__: {
      label: 'Voice document (Markdown)',
      help: 'Synthesized tone-of-voice and example phrasings. Drives every outbound message generator.',
    },
  },
  icp: {
    __file__: {
      label: 'ICP segments (YAML)',
      help: 'One segment per entry. Synthesis populates roles, industries, decision makers, pain points, disqualifiers.',
    },
  },
  positioning: {
    __file__: {
      label: 'Positioning one-pager (Markdown)',
      help: 'One file per battlecard plus the master one-pager. Edits here flow into proposals and message scaffolds.',
    },
  },
  qualification_rules: {
    __file__: {
      label: 'Qualification rules (Markdown)',
      help: 'Free-form rules + regex used by the qualifier. Each line that starts with `(?i)` is treated as a regex include.',
    },
  },
  campaign_templates: {
    __file__: {
      label: 'Campaign templates (YAML)',
      help: 'Connect note + DM templates. Token placeholders like `{{first_name}}` are substituted at send time.',
    },
  },
  search_queries: {
    __file__: {
      label: 'Search queries (one per line)',
      help: 'Used by the prospector to seed candidate searches. Stay specific — broad queries waste credits.',
    },
  },
  config: {
    __file__: {
      label: 'Tenant config (YAML)',
      help: 'Provider preferences and goals. Provider keys live in your env, not here.',
    },
  },
}

/**
 * Resolve help for a `(sectionId, fieldKey)` pair, falling back to a
 * minimal label derived from the field key when no entry is registered.
 * This guarantees the form always has a label even if the schema gains a
 * field before the help registry catches up.
 */
export function resolveFieldHelp(sectionId: string, fieldKey: string): FieldHelp {
  const section = SETUP_FIELD_HELP[sectionId]
  if (section && section[fieldKey]) return section[fieldKey]
  // Derive a Title Case label from the leaf segment of the key.
  const leaf = fieldKey.replace(/\[\]$/, '').split('.').pop() ?? fieldKey
  const label = leaf
    .replace(/[_-]+/g, ' ')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .split(/\s+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ')
  return { label, help: '' }
}
