import { atom } from 'jotai'
import type { GTMFramework } from '@/lib/framework/types'

// Whether the onboarding modal is open
export const onboardingOpenAtom = atom<boolean>(false)

// Current step index (0-based)
export const onboardingStepAtom = atom<number>(0)

// Data collected during onboarding
export const onboardingDataAtom = atom<{
  websiteUrl: string
  linkedinUrl: string
  uploadedFiles: Array<{ name: string; content: string }>
  extractedFramework: Partial<GTMFramework> | null
  followUpAnswers: Record<string, string>
}>({
  websiteUrl: '',
  linkedinUrl: '',
  uploadedFiles: [],
  extractedFramework: null,
  followUpAnswers: {},
})

// Processing state for the AI extraction step
export const onboardingProcessingAtom = atom<boolean>(false)

// Follow-up questions generated by Claude
export const onboardingQuestionsAtom = atom<Array<{
  id: string
  question: string
  field: string
  inputType: 'text' | 'textarea' | 'select' | 'multi-select'
  options?: string[]
}>>([])
